"""Initial migration.

Revision ID: 56017c8d412e
Revises: 
Create Date: 2025-03-09 16:09:21.359843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56017c8d412e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=128), nullable=False),
    sa.Column('degree', sa.String(length=128), nullable=False),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    # ### end Alembic commands ###
